services:
    Maps_red\OpenIdConnectBundle\Security\GuardAuthenticator:
        arguments: ['@Maps_red\OpenIdConnectBundle\Security\User\UserProvider', "@router"]
        public: true


    Maps_red\OpenIdConnectBundle\Security\User\UserProvider:
        arguments:
            - '%openid_connect.issuer%'
            - '%openid_connect.client_id%'
            - '%openid_connect.client_secret%'
            - '%openid_connect.parameters%'
        public: true
