services:
    Maps_red\OpenIDConnectBundle\Security\GuardAuthenticator:
        arguments: ['@Maps_red\OpenIDConnectBundle\Security\User\UserProvider', "@router"]
        public: true


    Maps_red\OpenIDConnectBundle\Security\User\UserProvider:
        arguments:
            - '%open_id_connect.issuer%'
            - '%open_id_connect.client_id%'
            - '%open_id_connect.client_secret%'
            - '%open_id_connect.parameters%'
        public: true
